#!/usr/bin/env node
/**
 * apply-profile.mjs — resolve a feature profile from feature-manifest.json and
 * apply it to the working tree.
 *
 * The template ships every feature. A new project starts from the `slim`
 * persona (core only) and opts in to what it needs, so nobody inherits the
 * property-management stack by default.
 *
 *   node scripts/apply-profile.mjs plan   --persona=slim
 *   node scripts/apply-profile.mjs apply  --persona=vacation_rental --mode=soft
 *   node scripts/apply-profile.mjs apply  --features=email,rentals --mode=prune
 *   node scripts/apply-profile.mjs add    rentals residents
 *   node scripts/apply-profile.mjs status
 *
 * Modes:
 *   soft  (default) — write .claudeignore so Claude Code skips unused features.
 *                     Nothing is deleted; fully reversible.
 *   prune           — additionally delete the unused paths from disk.
 *
 * `apply` refuses to run with a dirty working tree unless --force is given,
 * because prune deletes files and you want a clean diff to review.
 */

import { readFileSync, writeFileSync, existsSync, rmSync, statSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const MANIFEST = join(ROOT, 'feature-manifest.json');
const STATE = join(ROOT, '.setup-state.json');
const CLAUDEIGNORE = join(ROOT, '.claudeignore');

// Manifest keys that are not features.
const NON_FEATURES = new Set(['_meta', 'personas', 'core']);
// Path-valued fields on a feature entry.
const PATH_FIELDS = ['dirs', 'pages', 'shared', 'pollers'];

const die = (msg) => { console.error(`error: ${msg}`); process.exit(1); };

function loadManifest() {
  if (!existsSync(MANIFEST)) die(`feature-manifest.json not found at ${MANIFEST}`);
  try { return JSON.parse(readFileSync(MANIFEST, 'utf8')); }
  catch (e) { die(`feature-manifest.json is not valid JSON: ${e.message}`); }
}

const featureNames = (m) =>
  Object.keys(m).filter((k) => !NON_FEATURES.has(k) && !k.startsWith('_'));

/** Feature paths, and the edge functions it owns. */
function featurePaths(entry) {
  const paths = [];
  for (const f of PATH_FIELDS) for (const p of entry?.[f] ?? []) paths.push(p);
  for (const fn of entry?.edgeFunctions ?? []) paths.push(`supabase/functions/${fn}/`);
  return paths;
}

/** Expand a feature set over its `dependencies` edges. */
function resolveDeps(manifest, requested) {
  const known = new Set(featureNames(manifest));
  const out = new Set();
  const added = [];
  const visit = (name, via) => {
    if (!known.has(name)) die(`unknown feature "${name}"${via ? ` (required by ${via})` : ''}`);
    if (out.has(name)) return;
    out.add(name);
    if (via) added.push(`${name} (required by ${via})`);
    for (const dep of manifest[name].dependencies ?? []) visit(dep, name);
  };
  for (const f of requested) visit(f, null);
  return { features: [...out], pulledIn: added };
}

/**
 * Paths to exclude: everything owned by a disabled feature, minus anything
 * also owned by core or by an enabled feature. A path shared between two
 * features must survive if either is on.
 */
function computeExclusions(manifest, enabled) {
  const on = new Set(enabled);
  const keep = new Set(featurePaths(manifest.core));
  for (const p of manifest.core?.dirs ?? []) keep.add(p);
  for (const name of featureNames(manifest)) {
    if (on.has(name)) for (const p of featurePaths(manifest[name])) keep.add(p);
  }
  const drop = new Map(); // path -> owning features
  for (const name of featureNames(manifest)) {
    if (on.has(name)) continue;
    for (const p of featurePaths(manifest[name])) {
      if (keep.has(p)) continue;
      if (!drop.has(p)) drop.set(p, []);
      drop.get(p).push(name);
    }
  }
  return drop;
}

/** Project-specific content the template never ships. */
function baseExclusions(manifest) {
  const spec = manifest['_your-app_specific'] ?? {};
  return [
    ...(spec.dirs ?? []),
    ...(spec.docs ?? []),
    ...(spec.edgeFunctions ?? []).map((f) => `supabase/functions/${f}/`),
    'package-lock.json',
    'styles/tailwind.out.css',
  ];
}

function gitDirty() {
  try {
    return execFileSync('git', ['status', '--porcelain'], { cwd: ROOT, encoding: 'utf8' }).trim() !== '';
  } catch { return false; }
}

function readState() {
  if (!existsSync(STATE)) return null;
  try { return JSON.parse(readFileSync(STATE, 'utf8')); } catch { return null; }
}

function writeState(patch) {
  const prev = readState() ?? {};
  const next = { ...prev, ...patch };
  writeFileSync(STATE, JSON.stringify(next, null, 2) + '\n');
  return next;
}

function writeClaudeignore(manifest, exclusions) {
  const lines = [
    '# Generated by scripts/apply-profile.mjs — do not edit by hand.',
    '# Re-run the script to regenerate. Paths here are features this project',
    '# has not enabled; Claude Code skips them to keep search scope small.',
    '',
    '# Template/source content never shipped to a project:',
    ...baseExclusions(manifest),
    '',
    '# Disabled features:',
    ...[...exclusions.keys()].sort(),
    '',
  ];
  writeFileSync(CLAUDEIGNORE, lines.join('\n'));
}

function parseArgs(argv) {
  const opts = { mode: 'soft', _: [] };
  for (const a of argv) {
    if (a.startsWith('--persona=')) opts.persona = a.slice(10);
    else if (a.startsWith('--features=')) opts.features = a.slice(11).split(',').map((s) => s.trim()).filter(Boolean);
    else if (a.startsWith('--mode=')) opts.mode = a.slice(7);
    else if (a === '--force') opts.force = true;
    else if (a === '--dry-run') opts.dryRun = true;
    else if (a.startsWith('-')) die(`unknown flag ${a}`);
    else opts._.push(a);
  }
  if (!['soft', 'prune'].includes(opts.mode)) die(`--mode must be "soft" or "prune", got "${opts.mode}"`);
  return opts;
}

function selectFeatures(manifest, opts, fallbackToState = false) {
  if (opts.features) return opts.features;
  if (opts.persona) {
    const p = manifest.personas?.[opts.persona];
    if (!p) die(`unknown persona "${opts.persona}". Known: ${Object.keys(manifest.personas ?? {}).join(', ')}`);
    return p.features ?? [];
  }
  if (fallbackToState) {
    const st = readState();
    if (st?.enabled_features) return st.enabled_features;
  }
  return manifest.personas?.slim?.features ?? [];
}

function report(manifest, enabled, pulledIn, exclusions) {
  console.log(`\nEnabled features (${enabled.length}): ${enabled.length ? enabled.join(', ') : '(core only — slim)'}`);
  if (pulledIn.length) console.log(`Pulled in by dependencies: ${pulledIn.join(', ')}`);
  const existing = [...exclusions.keys()].filter((p) => existsSync(join(ROOT, p)));
  console.log(`\nPaths to exclude: ${exclusions.size} (${existing.length} present on disk)`);
  for (const p of existing.sort()) console.log(`  - ${p}  [${exclusions.get(p).join(', ')}]`);
  const missing = exclusions.size - existing.length;
  if (missing) console.log(`  (${missing} manifest paths are already absent)`);
  return existing;
}

function main() {
  const [cmd, ...rest] = process.argv.slice(2);
  const manifest = loadManifest();

  if (!cmd || cmd === 'help' || cmd === '--help') {
    console.log(readFileSync(fileURLToPath(import.meta.url), 'utf8').split('*/')[0].replace(/^#!.*\n/, ''));
    console.log(`Personas: ${Object.keys(manifest.personas ?? {}).join(', ')}`);
    console.log(`Features: ${featureNames(manifest).join(', ')}`);
    return;
  }

  if (cmd === 'status') {
    const st = readState();
    if (!st) { console.log('No .setup-state.json — this project has not been profiled yet (template default: slim).'); return; }
    console.log(JSON.stringify(st, null, 2));
    return;
  }

  if (cmd === 'plan' || cmd === 'apply') {
    const opts = parseArgs(rest);
    const requested = selectFeatures(manifest, opts);
    const { features: enabled, pulledIn } = resolveDeps(manifest, requested);
    const exclusions = computeExclusions(manifest, enabled);
    const existing = report(manifest, enabled, pulledIn, exclusions);

    if (cmd === 'plan' || opts.dryRun) {
      console.log(`\n(plan only — nothing written. Re-run with "apply" and --mode=${opts.mode} to execute.)`);
      return;
    }
    if (gitDirty() && !opts.force) {
      die('working tree is dirty. Commit or stash first, or pass --force.\n' +
          '       apply rewrites .claudeignore and (with --mode=prune) deletes files.');
    }

    writeClaudeignore(manifest, exclusions);
    console.log(`\nWrote .claudeignore (${exclusions.size} excluded paths).`);

    if (opts.mode === 'prune') {
      let removed = 0;
      for (const p of existing) {
        rmSync(join(ROOT, p), { recursive: true, force: true });
        removed++;
      }
      console.log(`Pruned ${removed} paths from disk.`);
    }

    writeState({
      persona: opts.persona ?? (opts.features ? 'custom' : 'slim'),
      enabled_features: enabled,
      prune_mode: opts.mode === 'prune' ? 'full' : 'soft',
      updated_at: new Date().toISOString(),
      ...(readState()?.setup_started_at ? {} : { setup_started_at: new Date().toISOString() }),
    });
    console.log('Updated .setup-state.json.');
    if (opts.mode === 'prune') {
      console.log('\nReview with `git status`, then commit. To restore a feature later:');
      console.log('  node scripts/apply-profile.mjs add <feature>   (see docs for the restore step)');
    }
    return;
  }

  if (cmd === 'add') {
    const opts = parseArgs(rest);
    const toAdd = opts._;
    if (!toAdd.length) die('usage: apply-profile.mjs add <feature> [<feature>...]');
    const st = readState();
    const current = st?.enabled_features ?? manifest.personas?.slim?.features ?? [];
    const { features: enabled, pulledIn } = resolveDeps(manifest, [...new Set([...current, ...toAdd])]);
    const exclusions = computeExclusions(manifest, enabled);

    console.log(`Adding: ${toAdd.join(', ')}`);
    if (pulledIn.length) console.log(`Dependencies pulled in: ${pulledIn.join(', ')}`);

    const restore = [];
    for (const f of toAdd) for (const p of featurePaths(manifest[f] ?? {})) {
      if (!existsSync(join(ROOT, p))) restore.push(p);
    }

    if (opts.dryRun) { console.log('(dry run — nothing written)'); return; }

    writeClaudeignore(manifest, exclusions);
    writeState({ enabled_features: enabled, updated_at: new Date().toISOString() });
    console.log(`Wrote .claudeignore and updated .setup-state.json (${enabled.length} features enabled).`);

    if (restore.length && st?.prune_mode === 'full') {
      console.log(`\n${restore.length} path(s) were pruned from disk and must be restored from the template:`);
      for (const p of restore) console.log(`  - ${p}`);
      console.log('\nRestore them with:');
      console.log('  git remote add infra-upstream https://github.com/YOUR_ORG/alpacapps-infra.git  # once');
      console.log('  git fetch infra-upstream main');
      console.log(`  git checkout infra-upstream/main -- ${restore.join(' ')}`);
      console.log('\nThen apply any DB tables the feature needs (see `dbTables` in feature-manifest.json).');
    }
    return;
  }

  die(`unknown command "${cmd}". Try: plan, apply, add, status, help`);
}

main();
